### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [mittal-parth/Cluboard#5]
👋 Hi @mittal-parth ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX.

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/mittal-parth/Inventory-Management-Django/issues/6
- [x] https://github.com/mittal-parth/Inventory-Management-Django/issues/7
- [x] https://github.com/mittal-parth/Inventory-Management-Django/issues/8

**Comment by mittal-parth** [comment]
Hi @ericdrosado! 👋
Thank you so much for considering my repo worthy of being part of the Community Exchange program! Excited to work on this! 🤩

I have understood the requirements. I will be making the PRs and updating you about the same.

**Comment by mittal-parth** [comment]
Hi @ericdrosado! May I know the steps forward?

**Comment by ericdrosado** [comment]
👋 Hi @mittal-parth I will reach out later this week with an invitation to submit your repository.

**Comment by mittal-parth** [comment]
Hi @ericdrosado! 
I have submitted my repo for CX. Can I rename my repository?

**Comment by ericdrosado** [comment]
Thank you for submitting your repository! You are more than welcome to change the name of your repository. The change won't happen immediately on CX since we update repos on a certain cadence. Please feel free to change it, and if you don't see the name change by the next day, please let me know.
